/**
 * Seed & Mock Data for Autonomous / Guest Mode and Demo Testing
 * Provides immediate functional data for Students, Recruiters, and Institutions.
 */

export const MOCK_USERS = [
  {
    uid: 'student_1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@college.edu.in',
    photoURL: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop',
    role: 'student',
    createdAt: new Date().toISOString(),
  },
  {
    uid: 'student_2',
    name: 'Priya Patel',
    email: 'priya.patel@college.edu.in',
    photoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
    role: 'student',
    createdAt: new Date().toISOString(),
  },
  {
    uid: 'student_3',
    name: 'Rohan Verma',
    email: 'rohan.verma@college.edu.in',
    photoURL: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop',
    role: 'student',
    createdAt: new Date().toISOString(),
  },
  {
    uid: 'recruiter_1',
    name: 'Vikram Malhotra',
    email: 'vikram@techcorp-talent.com',
    photoURL: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop',
    role: 'recruiter',
    createdAt: new Date().toISOString(),
  },
  {
    uid: 'institution_1',
    name: 'Dr. Sunita Rao (Dean T&P)',
    email: 'placement@nitd.ac.in',
    photoURL: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop',
    role: 'institution_admin',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_STUDENTS = [
  {
    uid: 'student_1',
    collegeName: 'National Institute of Technology, Delhi',
    university: 'NIT Delhi',
    degree: 'B.Tech',
    branch: 'Computer Science & Engineering',
    graduationYear: '2025',
    location: 'New Delhi, India',
    skills: [
      { name: 'Python', level: 'Advanced' },
      { name: 'React', level: 'Intermediate' },
      { name: 'JavaScript', level: 'Advanced' },
      { name: 'SQL', level: 'Intermediate' },
      { name: 'Git & GitHub', level: 'Advanced' },
    ],
    resumeURL: 'https://example.com/resumes/aarav-sharma-cv.pdf',
    linkedinUrl: 'https://linkedin.com/in/aarav-sharma-dev',
    githubUrl: 'https://github.com/aaravsharma-codes',
    about: 'Passionate computer science undergrad focused on scalable web apps and data analytics. Built several open-source React and Node.js projects.',
  },
  {
    uid: 'student_2',
    collegeName: 'National Institute of Technology, Delhi',
    university: 'NIT Delhi',
    degree: 'B.Tech',
    branch: 'Data Science & AI',
    graduationYear: '2025',
    location: 'Gurugram, India',
    skills: [
      { name: 'Python', level: 'Advanced' },
      { name: 'Machine Learning', level: 'Advanced' },
      { name: 'Deep Learning', level: 'Intermediate' },
      { name: 'Data Analysis', level: 'Advanced' },
      { name: 'SQL', level: 'Advanced' },
    ],
    resumeURL: 'https://example.com/resumes/priya-patel-cv.pdf',
    linkedinUrl: 'https://linkedin.com/in/priyapatel-ai',
    githubUrl: 'https://github.com/priyapatel-data',
    about: 'Data enthusiast interested in predictive modeling, computer vision, and building end-to-end ML pipelines with PyTorch and Scikit-learn.',
  },
  {
    uid: 'student_3',
    collegeName: 'National Institute of Technology, Delhi',
    university: 'NIT Delhi',
    degree: 'B.Tech',
    branch: 'Information Technology',
    graduationYear: '2026',
    location: 'Noida, India',
    skills: [
      { name: 'Java', level: 'Advanced' },
      { name: 'Spring Boot', level: 'Intermediate' },
      { name: 'SQL', level: 'Intermediate' },
      { name: 'Docker', level: 'Beginner' },
    ],
    resumeURL: 'https://example.com/resumes/rohan-verma-cv.pdf',
    linkedinUrl: 'https://linkedin.com/in/rohanverma-backend',
    githubUrl: 'https://github.com/rohanverma-dev',
    about: 'Backend systems engineer exploring distributed systems, microservices architectures, and cloud deployments.',
  },
];

export const MOCK_RECRUITERS = [
  {
    uid: 'recruiter_1',
    companyName: 'NexGen Cloud Solutions',
    industry: 'Enterprise Software & Cloud',
    description: 'A global technology innovator building hybrid cloud and AI-driven workflow platforms.',
    website: 'https://nexgencloud.io',
    location: 'Bengaluru, India',
    logoURL: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop',
  },
];

export const MOCK_INSTITUTIONS = [
  {
    uid: 'institution_1',
    institutionName: 'National Institute of Technology, Delhi',
    university: 'Institute of National Importance',
    location: 'Delhi, India',
    website: 'https://nitdelhi.ac.in',
  },
];

export const MOCK_OPPORTUNITIES = [
  {
    id: 'opp_1',
    recruiterId: 'recruiter_1',
    companyName: 'NexGen Cloud Solutions',
    title: 'Full Stack Web Developer Intern',
    type: 'Internship',
    description: 'Join our core platform engineering team to build scalable frontend components and secure RESTful microservices.',
    requiredSkills: ['Python', 'React', 'SQL', 'JavaScript'],
    preferredSkills: ['Docker', 'AWS'],
    location: 'Bengaluru (Hybrid)',
    duration: '6 Months',
    compensation: '₹35,000 / month',
    deadline: '2026-10-15',
    openings: 5,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'opp_2',
    recruiterId: 'recruiter_1',
    companyName: 'NexGen Cloud Solutions',
    title: 'Machine Learning & AI Associate',
    type: 'Job',
    description: 'Work with LLMs, retrieval augmented generation, and customer analytics pipeline optimization.',
    requiredSkills: ['Python', 'Machine Learning', 'Data Analysis', 'SQL'],
    preferredSkills: ['Deep Learning', 'Docker'],
    location: 'Hyderabad (On-site)',
    duration: 'Full-time',
    compensation: '₹14,00,000 / annum',
    deadline: '2026-11-01',
    openings: 3,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'opp_3',
    recruiterId: 'recruiter_1',
    companyName: 'NexGen Cloud Solutions',
    title: 'DevOps & Cloud Infrastructure Intern',
    type: 'Internship',
    description: 'Help manage Kubernetes clusters, CI/CD GitHub workflows, and AWS Terraform scripts.',
    requiredSkills: ['Cloud Computing (AWS/GCP)', 'Docker', 'Kubernetes', 'DevOps'],
    preferredSkills: ['Python', 'Git & GitHub'],
    location: 'Remote',
    duration: '3 Months',
    compensation: '₹30,000 / month',
    deadline: '2026-09-30',
    openings: 2,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'opp_4',
    recruiterId: 'recruiter_external',
    companyName: 'Innovate UI Labs',
    title: 'UI/UX Product Design Intern',
    type: 'Internship',
    description: 'Transform complex enterprise data into intuitive, human-centered web design systems and clickable Figma prototypes.',
    requiredSkills: ['UI/UX Design', 'Figma', 'React'],
    preferredSkills: ['JavaScript', 'CSS'],
    location: 'Pune (Hybrid)',
    duration: '4 Months',
    compensation: '₹25,000 / month',
    deadline: '2026-10-20',
    openings: 2,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
];

export const MOCK_APPLICATIONS = [
  {
    id: 'app_1',
    studentId: 'student_1',
    opportunityId: 'opp_1',
    recruiterId: 'recruiter_1',
    status: 'interview',
    appliedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    zoomMeetingId: '849 2931 0482',
    zoomPassword: 'SIH26',
    zoomJoinUrl: 'https://zoom.us/j/84929310482?pwd=U2lIMjYwNDRJbnRlcnZpZXc',
    interviewDate: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    interviewType: 'Technical Architecture & Coding Round',
    interviewerName: 'Vikram Malhotra (NexGen Cloud Solutions)',
  },
  {
    id: 'app_2',
    studentId: 'student_2',
    opportunityId: 'opp_2',
    recruiterId: 'recruiter_1',
    status: 'shortlisted',
    appliedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app_3',
    studentId: 'student_3',
    opportunityId: 'opp_1',
    recruiterId: 'recruiter_1',
    status: 'under_review',
    appliedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_SAVED = [
  {
    studentId: 'student_1',
    opportunityId: 'opp_2',
    savedAt: new Date().toISOString(),
  },
];
